spring:
  application:
    name: express
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
server:
  port: 9090

express:
  client:
    domain: http://localhost
    port: 3000
