spring:
  application:
    name: express
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db/migration
server:
  port: 9090

express:
  client:
    domain: http://localhost
    port: 3000
