###
GET http://localhost:9090/api/v1/customers


###
POST http://localhost:9090/api/v1/customers
Content-Type: application/json

{
  "name": "엄태성",
  "phone": "01033334445",
  "address": "서울시 강남구 서초동",
  "recommendedBy": "JHS"
}