###
GET http://localhost:9090/api/v1/customers


###
POST http://localhost:9090/api/v1/customers
Content-Type: application/json

{
  "name": "김태희",
  "phone": "01033334444",
  "address": "서울시 강남구 압구정동",
  "recommendedBy": "주현수"
}