###
GET http://localhost:9090/api/v1/customers

###
GET http://localhost:9090/api/v1/customers?page=0&size=10


###
POST http://localhost:9090/api/v1/customers
Content-Type: application/json

{
  "name": "성시구",
  "phone": "01033331111",
  "address": "서울시 강남구 삼성동",
  "recommendedBy": "주현수"
}

###
PUT http://localhost:9090/api/v1/customers/2
Content-Type: application/json

{
  "name": "기라성",
  "phone": "01025393333",
  "address": "서울시 영등포구 대방동",
  "recommendedBy": "김상"
}

###
DELETE http://localhost:9090/api/v1/customers/7