create table customers
(
    id             bigint generated by default as identity
        primary key,
    address        varchar(255) not null,
    created_at     timestamp(6),
    name           varchar(255) not null,
    phone          varchar(255) not null,
    recommended_by varchar(255),
    updated_at     timestamp(6)
);

create table products
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    description varchar(255),
    name        varchar(255) not null
        constraint uko61fmio5yukmmiqgnxf8pnavn
            unique,
    price       integer      not null
);

alter table products
    owner to postgres;


create table orders
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    customer_id bigint
        constraint fkpxtb8awmi0dk6smoh2vp1litg
            references customers,
    product_id  bigint
        constraint fkkp5k52qtiygd8jkag4hayd0qg
            references products
);

alter table orders
    owner to postgres;


